### ISSUE TITLE
Thanks for the submission, some comments

### ISSUE THREAD

**Issue by saurabh-jain-jukin** [Hariom0000/CovidBackedn#1]
HI Hariom,
Thanks for putting all this together. It looks really good and promising.
The code is clean, easy to read, modular and well structured.

I had few comments to share. No need to make changes but just wanted to understand your perspective on that:
- You made a decision to load the data during application startup. What is the thought process behind that?
- We always render the stale data from DB and only go to the WS when its not in DB. Do you think it is a good design?
- In DataLoader, you didn't do any exception handling. Like what if the data is not in the DB and WS is also down? How or what to display to the user.

Apart from this I am good.
Looking forward to hear from you soon on this.

Thanks
Saurabh Jain

**Comment by saurabh-jain-jukin** [comment]
Some more review comments based on 2nd pass:

1. During stack start, you are running DataLoader. However, this is failing due to the attached reason. I had to comment line 43 (//getLatestTotal();) to get pass this and run the backend app. Due to this no data is persisted in DB.
Now when I try to goto Home, it is throwing
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[na:1.8.0_261]
	at java.util.ArrayList.get(ArrayList.java:435) ~[na:1.8.0_261]
	at com.covid19.covid.service.serviceImpl.CountryReadServiceImpl.getLatestTotal(CountryReadServiceImpl.java:84) ~[classes/:na]
```
Do you know why this occurred What changes can we make to make it work if data is not in DB?

2. When I search by countryName and enter "America", its giving below error:
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.covid19.covid.DataLoader.getCountryCovidByName(DataLoader.java:63) ~[classes/:na]
	at com.covid19.covid.service.serviceImpl.CountryWriteServiceImpl.getCountryCovidAndSaveByName(CountryWriteServiceImpl.java:22) ~[classes/:na]
```
Do you know why this occurred and how can we fix this?

3. Same is the behaviour when I search by countryCode and enter "TEST" as input.
4. When tried to search using countryCode and my internet is down, I get the following error:
```
GET request for "https://covid-19-data.p.rapidapi.com/country/code": covid-19-data.p.rapidapi.com; nested exception is java.net.UnknownHostException: covid-19-data.p.rapidapi.com] with root cause

java.net.UnknownHostException: covid-19-data.p.rapidapi.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:196) ~[na:1.8.0_261]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394) ~[na:1.8.0_261]
.
.
.
.
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:739) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:583) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at com.covid19.covid.DataLoader.getCountryCovidByCode(DataLoader.java:68) ~[classes/:na]
```
Can you identify the root cause and how can we mitigate it?

5. Can we improve the logging by capturing the REST API response so that we can analyse it during failures?
6. Can we ensure countries added to favourites are displayed first in the list of countries?

Thanks
